### ISSUE TITLE
OpaqueToken is deprecated

### ISSUE THREAD

**Issue by yasinfp** [Rebilly/ReDoc#232]
when executing 
`npm run clean:aot && npm run build:sass && npm run webpack:prod` 
npm throws an exception contains about angular/core. 
The exception is; 
> Error: undefined, resolving symbol OpaqueToken in /Users/yfpayalan/workspace/ReDoc/node_modules/@angular/core/src/di/opaque_token.d.ts

After some research [that link](https://github.com/angular/angular/issues/14763) tells OpaqueToken has been deprecated in angular/core module. I think it should be changed while webpack bundling process.
Here is my full output log.

> Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: undefined, resolving symbol OpaqueToken in /Users/yfpayalan/workspace/ReDoc/node_modules/@angular/core/src/di/opaque_token.d.ts
    at SyntaxError.BaseError [as constructor] (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at simplifyInContext (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:25783:27)
    at StaticReflector.simplify (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:25795:17)
    at StaticReflector.annotations (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:18272:64)
    at addNgModule (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:25053:62)
    at /Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:25064:18
    at Array.forEach (native)
    at _createNgModules (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:25063:30)
    at analyzeNgModules (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:24938:18)
    at analyzeAndValidateNgModules (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:24948:39)
    at AotCompiler.compileAll (/Users/yfpayalan/workspace/ReDoc/node_modules/@angular/compiler/bundles/compiler.umd.js:24672:22)
    at CodeGenerator.codegen (/Users/yfpayalan/workspace/ReDoc/modules/@angular/compiler-cli/src/codegen.ts:41:10)
    at /Users/yfpayalan/workspace/ReDoc/node_modules/src/main.ts:20:84
    at Object.main (/Users/yfpayalan/workspace/tools/@angular/tsc-wrapped/src/main.ts:60:12)
    at Object.runInternal (/Users/yfpayalan/workspace/ReDoc/node_modules/src/main.ts:25:10)
    at NgcWebpackPlugin.run (/Users/yfpayalan/workspace/ReDoc/node_modules/src/plugin.ts:102:7)
    at Compiler.<anonymous> (/Users/yfpayalan/workspace/ReDoc/node_modules/src/plugin.ts:78:53)
    at next (/Users/yfpayalan/workspace/ReDoc/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/Users/yfpayalan/workspace/ReDoc/node_modules/awesome-typescript-loader/src/watch-mode.ts:7:13)
    at Compiler.applyPluginsAsyncSeries (/Users/yfpayalan/workspace/ReDoc/node_modules/tapable/lib/Tapable.js:142:13)
    at /Users/yfpayalan/workspace/ReDoc/node_modules/webpack/lib/Compiler.js:214:8
    at next (/Users/yfpayalan/workspace/ReDoc/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.<anonymous> (/Users/yfpayalan/workspace/ReDoc/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:21:4)
    at Compiler.applyPluginsAsyncSeries (/Users/yfpayalan/workspace/ReDoc/node_modules/tapable/lib/Tapable.js:142:13)
    at Compiler.run (/Users/yfpayalan/workspace/ReDoc/node_modules/webpack/lib/Compiler.js:211:7)
    at processOptions (/Users/yfpayalan/workspace/ReDoc/node_modules/webpack/bin/webpack.js:359:12)
    at Object.<anonymous> (/Users/yfpayalan/workspace/ReDoc/node_modules/webpack/bin/webpack.js:363:1)

**Comment by RomanGotsiy** [comment]
I have just migrated to angular 4.0.0-rc.3 so this issue should be fixed now.

**Comment by yasinfp** [comment]
Yes. it works smoothly 
Thanks.
