### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by baikhos** [Rebilly/ReDoc#343]
An error is generated by executing the instruction below.
I want to know how to solve this problem.

$ npm start

> redoc@1.18.1 start /data/htdocs/redoc
> webpack-dev-server --config build/webpack.dev.js --content-base demo

Error: listen EADDRINUSE 127.0.0.1:9000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redoc@1.18.1 start: `webpack-dev-server --config build/webpack.dev.js --content-base demo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redoc@1.18.1 start script 'webpack-dev-server --config build/webpack.dev.js --content-base demo'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redoc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config build/webpack.dev.js --content-base demo
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redoc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redoc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/htdocs/redoc/npm-debug.log

**Comment by baikhos** [comment]
solved it.
The port number has been modified from 9000 to another and normal operation has been normal.
