### ISSUE TITLE
TypeError: Cannot read property 'x-trace' of null

### ISSUE THREAD

**Issue by dobromir-bogatev** [Rebilly/ReDoc#443]
My redoc-cli serve was running adequately until suddenly this error appeared. I reverted the swagger.yaml file to its previous state before the error (I havent edited any other files), but the error persists and I cant seem to fix it.

```
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
TypeError: Cannot read property 'x-trace' of null
    at processPaths (C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:2496:18)
    at main (C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:2750:5)
    at C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:3100:25
    at step (C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:1766:23)
    at Object.next (C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:1747:53)
    at onFulfilled (C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\co\index.js:65:19)
    at C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\co\index.js:50:10)
    at C:\Users\SkyLordPanglot\AppData\Roaming\npm\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:3082:9
```

**Comment by RomanGotsiy** [comment]
Then closing this issue.
