### ISSUE TITLE
Non-JSON examples break ReDoc

### ISSUE THREAD

**Issue by cheald** [Rebilly/ReDoc#456]
Using 2.0-alpha18

The following definition breaks:
```yml
---
swagger: '2.0'
info:
  title: API
  version: v1
paths:
  "/foo":
    get:
      produces:
      - text/plain
      responses:
        '401':
          description: Access Denied
        '200':
          description: Success
          examples:
            text/plain: ''
        '422':
          description: Unprocessable Entity
          examples:
            text/plain: ''
        '403':
          description: Forbidden
```

With the following:

```
Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BnoSample%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Stack trace
Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BnoSample%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at d (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:604)
    at Or (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:39318)
    at https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:43986
    at a (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:44540)
    at s (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:44477)
    at beginWork (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:52949)
    at o (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:56296)
    at i (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:56562)
    at _ (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:59472)
    at v (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:72:59015)

ReDoc Version: 2.0.0-alpha.18 ```

Removing the empty example strings fixes it, but that's obviously not desirable. I'd like Redoc to just render those as given if they aren't valid JSON.

**Comment by Tsalmas-Anastasios** [comment]
Hello! I have the same exact problem. Do you know what is the solution for this?

**Comment by lornajane** [comment]
This is a very old issue which has been closed for a long time and relates to a different version of the software. Could you open a new issue with the details of what you are experiencing? Feel free to link to this one for context.
