### ISSUE TITLE
Cannot compile after fresh git clone

### ISSUE THREAD

**Issue by Gorjan-Relevantmobile** [Rebilly/ReDoc#487]
node version installed 8.11.1 on ubuntu 16.04, npm version 5.6.0
head at 8376068bfa1b5545eb33592d55c35a966e61e990

npm install returns

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-loader@7.1.2 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```

npm start returns

```
> redoc@2.0.0-alpha.18 start /opt/ReDoc
> webpack-dev-server --mode=development --env.playground --hot --config demo/webpack.config.ts

Starting type checking service...
Using 1 worker with 2048MB memory limit
ℹ ｢wds｣: Project is running at http://localhost:9090/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /opt/ReDoc/demo
(node:26822) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:26822) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
No type errors found
Version: typescript 2.8.3
Time: 24180ms
✖ ｢wdm｣:    376 modules

ERROR in ./src/components/ApiInfo/ApiInfo.tsx
Module build failed: SyntaxError: /opt/ReDoc/src/components/ApiInfo/ApiInfo.tsx: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (23:0)

  21 | 
  22 | @observer
> 23 | export class ApiInfo extends React.Component<ApiInfoProps> {
     | ^
  24 |   render() {
  25 |     const { store } = this.props;
  26 |     const { info, externalDocs } = store.spec;
    at _class.raise (/opt/ReDoc/node_modules/babylon/lib/index.js:779:15)
    at _class.parseDecorators (/opt/ReDoc/node_modules/babylon/lib/index.js:4120:14)
    at _class.parseStatement (/opt/ReDoc/node_modules/babylon/lib/index.js:3960:12)
    at _class.parseBlockOrModuleBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4510:23)
    at _class.parseBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4497:10)
    at _class.parseTopLevel (/opt/ReDoc/node_modules/babylon/lib/index.js:3939:10)
    at _class.parse (/opt/ReDoc/node_modules/babylon/lib/index.js:5301:17)
    at parse (/opt/ReDoc/node_modules/babylon/lib/index.js:10044:38)
    at parser (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:140:35)
    at normalizeFile (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:44:41)
    at runAsync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /opt/ReDoc/node_modules/@babel/core/lib/transform.js:34:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in ./src/components/ApiLogo/ApiLogo.tsx
Module build failed: SyntaxError: /opt/ReDoc/src/components/ApiLogo/ApiLogo.tsx: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (7:0)

   5 | 
   6 | @observer
>  7 | export class ApiLogo extends React.Component<{ info: OpenAPIInfo }> {
     | ^
   8 |   render() {
   9 |     const { info } = this.props;
  10 |     const logoInfo = info['x-logo'];
    at _class.raise (/opt/ReDoc/node_modules/babylon/lib/index.js:779:15)
    at _class.parseDecorators (/opt/ReDoc/node_modules/babylon/lib/index.js:4120:14)
    at _class.parseStatement (/opt/ReDoc/node_modules/babylon/lib/index.js:3960:12)
    at _class.parseBlockOrModuleBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4510:23)
    at _class.parseBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4497:10)
    at _class.parseTopLevel (/opt/ReDoc/node_modules/babylon/lib/index.js:3939:10)
    at _class.parse (/opt/ReDoc/node_modules/babylon/lib/index.js:5301:17)
    at parse (/opt/ReDoc/node_modules/babylon/lib/index.js:10044:38)
    at parser (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:140:35)
    at normalizeFile (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:44:41)
    at runAsync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /opt/ReDoc/node_modules/@babel/core/lib/transform.js:34:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in ./src/components/ContentItems/ContentItems.tsx
Module build failed: SyntaxError: /opt/ReDoc/src/components/ContentItems/ContentItems.tsx: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (13:0)

  11 | 
  12 | @observer
> 13 | export class ContentItems extends React.Component<{
     | ^
  14 |   items: ContentItemModel[];
  15 | }> {
  16 |   render() {
    at _class.raise (/opt/ReDoc/node_modules/babylon/lib/index.js:779:15)
    at _class.parseDecorators (/opt/ReDoc/node_modules/babylon/lib/index.js:4120:14)
    at _class.parseStatement (/opt/ReDoc/node_modules/babylon/lib/index.js:3960:12)
    at _class.parseBlockOrModuleBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4510:23)
    at _class.parseBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4497:10)
    at _class.parseTopLevel (/opt/ReDoc/node_modules/babylon/lib/index.js:3939:10)
    at _class.parse (/opt/ReDoc/node_modules/babylon/lib/index.js:5301:17)
    at parse (/opt/ReDoc/node_modules/babylon/lib/index.js:10044:38)
    at parser (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:140:35)
    at normalizeFile (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:44:41)
    at runAsync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /opt/ReDoc/node_modules/@babel/core/lib/transform.js:34:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in ./src/components/SideMenu/MenuItem.tsx
Module build failed: SyntaxError: /opt/ReDoc/src/components/SideMenu/MenuItem.tsx: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (16:0)

  14 | 
  15 | @observer
> 16 | export class MenuItem extends React.Component<MenuItemProps> {
     | ^
  17 |   ref: Element | null;
  18 | 
  19 |   activate = (evt: React.MouseEvent<HTMLElement>) => {
    at _class.raise (/opt/ReDoc/node_modules/babylon/lib/index.js:779:15)
    at _class.parseDecorators (/opt/ReDoc/node_modules/babylon/lib/index.js:4120:14)
    at _class.parseStatement (/opt/ReDoc/node_modules/babylon/lib/index.js:3960:12)
    at _class.parseBlockOrModuleBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4510:23)
    at _class.parseBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4497:10)
    at _class.parseTopLevel (/opt/ReDoc/node_modules/babylon/lib/index.js:3939:10)
    at _class.parse (/opt/ReDoc/node_modules/babylon/lib/index.js:5301:17)
    at parse (/opt/ReDoc/node_modules/babylon/lib/index.js:10044:38)
    at parser (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:140:35)
    at normalizeFile (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:44:41)
    at runAsync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /opt/ReDoc/node_modules/@babel/core/lib/transform.js:34:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in ./src/components/SideMenu/SideMenu.tsx
Module build failed: SyntaxError: /opt/ReDoc/src/components/SideMenu/SideMenu.tsx: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (11:0)

   9 | 
  10 | @observer
> 11 | export class SideMenu extends React.Component<{ menu: MenuStore }> {
     | ^
  12 |   private _updateScroll?: () => void;
  13 | 
  14 |   render() {
    at _class.raise (/opt/ReDoc/node_modules/babylon/lib/index.js:779:15)
    at _class.parseDecorators (/opt/ReDoc/node_modules/babylon/lib/index.js:4120:14)
    at _class.parseStatement (/opt/ReDoc/node_modules/babylon/lib/index.js:3960:12)
    at _class.parseBlockOrModuleBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4510:23)
    at _class.parseBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4497:10)
    at _class.parseTopLevel (/opt/ReDoc/node_modules/babylon/lib/index.js:3939:10)
    at _class.parse (/opt/ReDoc/node_modules/babylon/lib/index.js:5301:17)
    at parse (/opt/ReDoc/node_modules/babylon/lib/index.js:10044:38)
    at parser (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:140:35)
    at normalizeFile (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:44:41)
    at runAsync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /opt/ReDoc/node_modules/@babel/core/lib/transform.js:34:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in ./src/components/StickySidebar/StickyResponsiveSidebar.tsx
Module build failed: SyntaxError: /opt/ReDoc/src/components/StickySidebar/StickyResponsiveSidebar.tsx: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (71:0)

  69 | 
  70 | @observer
> 71 | export class StickyResponsiveSidebar extends React.Component<StickySidebarProps> {
     | ^
  72 |   stickyElement: Element;
  73 | 
  74 |   componentDidMount() {
    at _class.raise (/opt/ReDoc/node_modules/babylon/lib/index.js:779:15)
    at _class.parseDecorators (/opt/ReDoc/node_modules/babylon/lib/index.js:4120:14)
    at _class.parseStatement (/opt/ReDoc/node_modules/babylon/lib/index.js:3960:12)
    at _class.parseBlockOrModuleBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4510:23)
    at _class.parseBlockBody (/opt/ReDoc/node_modules/babylon/lib/index.js:4497:10)
    at _class.parseTopLevel (/opt/ReDoc/node_modules/babylon/lib/index.js:3939:10)
    at _class.parse (/opt/ReDoc/node_modules/babylon/lib/index.js:5301:17)
    at parse (/opt/ReDoc/node_modules/babylon/lib/index.js:10044:38)
    at parser (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:140:35)
    at normalizeFile (/opt/ReDoc/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:44:41)
    at runAsync (/opt/ReDoc/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /opt/ReDoc/node_modules/@babel/core/lib/transform.js:34:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in /opt/ReDoc/src/services/ScrollService.ts
./src/services/ScrollService.ts
[tsl] ERROR in /opt/ReDoc/src/services/ScrollService.ts(89,3)
      TS1241: Unable to resolve signature of method decorator when called as an expression.
ℹ ｢wdm｣: Failed to compile.
```

**Comment by Nocturnal316** [comment]
Anyone figure this out?

**Comment by ajermaky** [comment]
I am not a js export, but playing around with the files, seems like the compiler doesn't like export and  decorator being in the same line. i found that separating the export functionality from the class definition gets rid of compile errors. There is also one more issue regarding the throttle decorator found in ScrollService.ts. Removing this allowed it to compile, but there is a bug where when you scroll, it will automatically reset itself. Tracked down decorator issue to be in babel: https://github.com/babel/babel/pull/7869

Hopefully this will fix the issues.
