### ISSUE TITLE
Compile error after fresh git clone

### ISSUE THREAD

**Issue by nanov** [Rebilly/ReDoc#521]
This is what i get both with alpha 22 and 23 ( just caught the transition ;) ) :

```bash
> redoc@2.0.0-alpha.23 start /Users/mitkonanov/Projects/REDOC/ReDoc
> webpack-dev-server --mode=development --env.playground --hot --config demo/webpack.config.ts

Starting type checking service...
Using 1 worker with 2048MB memory limit
ℹ ｢wds｣: Project is running at http://localhost:9090/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/mitkonanov/Projects/REDOC/ReDoc/demo
No type errors found
Version: typescript 2.8.4
Time: 8221ms
✖ ｢wdm｣:    133 modules

ERROR in ./demo/playground/hmr-playground.tsx
Module build failed: SyntaxError: /Users/mitkonanov/Projects/REDOC/ReDoc/demo/playground/hmr-playground.tsx: Unexpected token, expected "</>" (14:13)

  12 |   render(
  13 |     <AppContainer>
> 14 |       <Redoc {...props} />
     |              ^
  15 |     </AppContainer>,
  16 |     document.getElementById('example'),
  17 |   );
    at _class.raise (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:3861:15)
    at _class.unexpected (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5190:16)
    at _class.expectRelational (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5131:12)
    at _class.tsParseTypeAssertion (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:9215:12)
    at _class.parseMaybeUnary (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:10112:21)
    at _class.tsParseTypeAssertion (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:9216:30)
    at _class.parseMaybeUnary (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:10112:21)
    at _class.parseExprOps (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5754:21)
    at _class.parseMaybeConditional (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5726:21)
    at _class.parseMaybeAssign (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5673:21)
    at _class.parseMaybeAssign (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:10099:87)
    at _class.parseExprListItem (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:6935:18)
    at _class.parseCallExpressionArguments (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:6064:22)
    at _class.parseSubscript (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5973:32)
    at _class.parseSubscript (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:9722:51)
    at _class.parseSubscripts (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5888:19)
    at _class.parseExprSubscripts (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5878:17)
    at _class.parseMaybeUnary (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5847:21)
    at _class.parseMaybeUnary (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:10114:54)
    at _class.parseExprOps (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5754:21)
    at _class.parseMaybeConditional (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5726:21)
    at _class.parseMaybeAssign (/Users/mitkonanov/Projects/REDOC/ReDoc/node_modules/@babel/parser/lib/index.js:5673:21)
ℹ ｢wdm｣: Failed to compile.
```

**Comment by nanov** [comment]
I can confirm that downgrading the following packages to **7.0.0-beta.47** solves the problem :

@babel/core, @babel/plugin-syntax-decorators, @babel/plugin-syntax-jsx, @babel/plugin-syntax-typescript.

**Comment by nanov** [comment]
Indeed, downgrading only ```babel/plugin-syntax-jsx``` is enough.

**Comment by RomanGotsiy** [comment]
fixed by https://github.com/Rebilly/ReDoc/commit/a8a7593da2d1f15d60414d5cfe05692652922a5e
