### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by gfelot** [Rebilly/ReDoc#624]
I wanted to generate my improved swagger doc with a new build of ReDoc using the CLI.
Worked perfectly before. Now : 

```
$ > npx redoc-cli bundle openapi.yaml
Warning: The "extend" API will be removed in the upcoming v4.0 release. Use styled(StyledComponent) instead. You can find more information here: https://github.com/styled-components/styled-components/issues/1546
Prerendering docs
TypeError: Cannot read property 'map' of undefined
    at Function.MenuBuilder.getTagsItems (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6584:29)
    at Function.MenuBuilder.getTagGroupsItems (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6565:38)
    at Function.MenuBuilder.buildStructure (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6525:49)
    at new SpecStore (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:5879:53)
    at new AppStore (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:7568:21)
    at Module.<anonymous> (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:7553:43)
    at step (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/gil/.npm/_npx/2991/lib/node_modules/redoc-cli/node_modules/tslib/tslib.js:104:62)
```

**Comment by RomanGotsiy** [comment]
Could you share your spec or at least minimal reproducible sample?

**Comment by gfelot** [comment]
My yaml file wasn't well formatted. I had a typo in `tags` object causing this.
