### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AlexRichter** [Rebilly/ReDoc#633]
```
RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at y (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:37:64046)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30759)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30371)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30528)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30371)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30528)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30371)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30528)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:99:30371)
```

I am getting this error when trying to load my OpenAPI 3.0 specification. I think it might have to do with circular references but I'm not sure.

**Comment by AlexRichter** [comment]
Maybe more helpfully:

```
react-dom.production.min.js:188 RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at y (openapi.ts:122)
    at e.mergeAllOf (OpenAPIParser.ts:275)
    at e.mergeAllOf (OpenAPIParser.ts:239)
    at e.mergeAllOf (OpenAPIParser.ts:249)
    at e.mergeAllOf (OpenAPIParser.ts:239)
    at e.mergeAllOf (OpenAPIParser.ts:249)
    at e.mergeAllOf (OpenAPIParser.ts:239)
    at e.mergeAllOf (OpenAPIParser.ts:249)
    at e.mergeAllOf (OpenAPIParser.ts:239)
```

**Comment by AlexRichter** [comment]
I re-wrote my schema, especially concentrating on the anyOf, oneOf and allOf relationships and it's now working so I think although my schema was valid it wasn't clear so going to close this.

**Comment by tylerbobella** [comment]
I am having this exact same issue and it only seems to happen with a path's response object has the `schema` property...
example:

```
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "originalRef": "Assignment",
                                "$ref": "#/definitions/Assignment"
                            }
                        }
                    },
...
```

If the schema object is removed everything works ok. Does anyone else have this issue? My stacktrace is the same as this issue's title.

**Comment by siimsoni** [comment]
I had a similar error recently. Seemed to be related to duplicated properties in `allOf` branches. Not sure if relevant, but the schemas differed slightly (one had `nullable: true`). Removing the duplicate branch fixed the issue for me.

Duplicating the branches was not intentional, but it was time consuming to trace down the problem, as the only indication of something wrong was this exception. Other tools worked fine.

**Comment by siimsoni** [comment]
Ran into the same error again. I had split the schema to "Shape" which lists all of the properties that the schema must have, without any more information, and "Properties" which contains the actual definitions...

```
{
  "openapi": "3.0.2",
  "info": {
    "title": "Test Case",
    "version": "v0.0.1",
    "description": "",
    "license": {
      "name": "",
      "url": ""
    }
  },
  "servers": [
    {
      "url": "https:\/\/localhost"
    }
  ],
  "paths": {
    "\/test": {
      "get": {
        "summary": "",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application\/json": {
                "schema": {
                  "$ref": "#\/components\/schemas\/Schema"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {hen trying so split shapes and properties
      "Schema": {
        "allOf": [
          {
            "$ref": "#\/components\/schemas\/Shape"
          },
          {
            "$ref": "#\/components\/schemas\/Properties"
          }
        ]
      },
      "Properties": {
        "type": "object",
        "properties": {
          "children": {
            "type": "array",
            "items": {
              "$ref": "#\/components\/schemas\/Schema"
            }
          }
        }
      },
      "Shape": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "children": {}
        }
      }
    }
  }
}
```
