### ISSUE TITLE
Error: Cannot find module 'mobx' from 'redoc.lib.js'

### ISSUE THREAD

**Issue by auahmed** [Rebilly/ReDoc#639]
I'm getting this strange error whenever I try to run my jest test. It was working fine previously but all of a sudden it started to fail.

````
FAIL  src/components/Layout/Layout.test.js
  ● Test suite failed to run

    Cannot find module 'mobx' from 'redoc.lib.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/redoc/bundles/redoc.lib.js:398:18)
      at __webpack_require__ (node_modules/redoc/bundles/redoc.lib.js:36:30)
      at Module.<anonymous> (node_modules/redoc/bundles/redoc.lib.js:5353:22)
      at __webpack_require__ (node_modules/redoc/bundles/redoc.lib.js:36:30)

````

im using version 2.0.0-alpha.38 and noticed that there was an error similar to this resolved for cli in alpha 30 i think (https://github.com/Rebilly/ReDoc/issues/576).

and i am importing to use redoc in my code by:
````
import { RedocStandalone } from 'redoc';
````

Thanks!

**Comment by RomanGotsiy** [comment]
Just install mobx: `npm install mobx@^4.3.1`.

`mobx` has been moved to peerDependencies so it is not installed automatically.
