### ISSUE TITLE
redoc alpha versions are marked as 'latest'

### ISSUE THREAD

**Issue by adamdecaf** [Rebilly/ReDoc#674]
`2.0.0-alpha.40` is currently the [latest released version](https://www.npmjs.com/package/redoc), but it seems to break. I'm all for opt-in beta testing, but I had to specify `1.22.2` to resolve my build.

Here's the output: 

```
Step 1/16 : FROM node:8-jessie as builder
8-jessie: Pulling from library/node
Status: Downloaded newer image for node:8-jessie
 ---> 6f62c0cdc461
Step 2/16 : RUN npm update -g && npm install -g --save mobx styled-components react react-dom redoc redoc-cli speccy
 ---> Running in 415d10242736
/usr/local/bin/redoc-cli -> /usr/local/lib/node_modules/redoc-cli/index.js
/usr/local/bin/speccy -> /usr/local/lib/node_modules/speccy/speccy.js
> styled-components@3.4.10 postinstall /usr/local/lib/node_modules/redoc-cli/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0
Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components
> styled-components@4.0.0 postinstall /usr/local/lib/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0
Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
npm WARN redoc@2.0.0-alpha.40 requires a peer of mobx@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN redoc@2.0.0-alpha.40 requires a peer of styled-components@^3.4.0 but none is installed. You must install peer dependencies yourself.
+ styled-components@4.0.0
+ redoc@2.0.0-alpha.40
+ react@16.5.2
+ react-dom@16.5.2
+ mobx@5.5.0
+ redoc-cli@0.6.4
+ speccy@0.8.2
added 347 packages from 261 contributors in 13.376s
 ---> e3dc310af773
Removing intermediate container 415d10242736
Step 3/16 : COPY openapi.yaml openapi.yaml
 ---> fbfa2c03d7fb
Step 4/16 : RUN speccy lint openapi.yaml
 ---> Running in 548400ebd41d
Specification is valid, with 0 lint errors
 ---> 885cbe55e497
Removing intermediate container 548400ebd41d
Step 5/16 : RUN redoc-cli bundle openapi.yaml
 ---> Running in ca98fbd45410
/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:7244
injectGlobal(perfect_scrollbar_templateObject_1 || (perfect_scrollbar_templateObject_1 = external_tslib_["__makeTemplateObject"](["", ""], ["", ""])), perfect_scrollbar_default.a && perfect_scrollbar_default.a.toString());
^
TypeError: injectGlobal is not a function
    at Module.<anonymous> (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:7244:1)
    at __webpack_require__ (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:36:30)
    at /usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:100:18
    at /usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:103:10
    at webpackUniversalModuleDefinition (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:9:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:16:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
The command '/bin/sh -c redoc-cli bundle openapi.yaml' returned a non-zero code: 1
make: *** [build] Error 1
```

**Comment by RomanGotsiy** [comment]
You have a warning in your logs with the exact issue cause:

> npm WARN redoc@2.0.0-alpha.40 requires a peer of styled-components@^3.4.0 but none is installed. You must install peer dependencies yourself.

As far as I can see, you have `styled-components@4.0.0` installed which is incompatible with `3.x` (has a few breaking changes, in particular, `injectGlobal` has been removed).
Install `3.4.x` version of styled-components to fix this.

I will update ReDoc to be compatible with the latest styled-components in a few weeks toghether with other dependencies update.
