### ISSUE TITLE
Invalid Spec Leads to Error Without Init Callback

### ISSUE THREAD

**Issue by rosshardy** [Rebilly/ReDoc#690]
Hello. In ReDoc 2.0.0-alpha.40 when generating ReDoc from a YAML file with a path with an empty tag (only the hyphen) ReDoc results in a "Something went wrong..." page with the below stack trace. The callback provided to init() is not invoked, so the surrounding application cannot recover from the error. 

```
slugify: string argument expected
Stack trace
Error: slugify: string argument expected
    at t (http://localhost:9000/scripts/redoc.standalone.js:52:44272)
    at ae (http://localhost:9000/scripts/redoc.standalone.js:99:16985)
    at new e (http://localhost:9000/scripts/redoc.standalone.js:99:38568)
    at Function.e.getTagsItems (http://localhost:9000/scripts/redoc.standalone.js:99:51355)
    at Function.e.buildStructure (http://localhost:9000/scripts/redoc.standalone.js:99:50551)
    at new <anonymous> (http://localhost:9000/scripts/redoc.standalone.js:99:38384)
    at new e (http://localhost:9000/scripts/redoc.standalone.js:105:28591)
    at t.makeStore (http://localhost:9000/scripts/redoc.standalone.js:99:60285)
    at t.render (http://localhost:9000/scripts/redoc.standalone.js:99:61129)
    at Ai (http://localhost:9000/scripts/redoc.standalone.js:68:62703)

ReDoc Version: 2.0.0-alpha.40 
Commit: 8f7fccc
```

**Comment by RomanGotsiy** [comment]
> (only the hyphen)

is not an empty tag. It is equivalent to:

```yaml
- null
```

So this is not valid spec as tags should be [an array of `string`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-8)

![image](https://user-images.githubusercontent.com/3975738/48003276-ad6e0980-e116-11e8-84e4-cd002b9d1ded.png)


To fix your spec you can use empty string:

```yaml
- ""
```

**Comment by rosshardy** [comment]
@RomanGotsiy The issue is not the validity of the spec. The issue is that there is no way to recover from this in a solution leveraging ReDoc because the callback on init() is not honored. The ReDoc documentation says that the callback is called in the cases of an error. It is not called in the case of of an invalid spec.

**Comment by RomanGotsiy** [comment]
@rosshardy ahh, got it. Sorry.
Reopening.

**Comment by rosshardy** [comment]
For additional context of the use case: we are trying to build a VSCode plugin which previews specs real-time as they are being built out or modified. However when the user edits tags and clears the tag out, the preview bombs out and there's no apparent way to recover ReDoc after the user corrects the spec.

**Comment by RomanGotsiy** [comment]
> For additional context of the use case: we are trying to build a VSCode plugin which previews specs real-time as they are being built out or modified.

😲This sounds super exciting! Is there any chance I can take a sneak peek of it?

I will look into the issue ASAP (most likely tomorrow morning).

**Comment by rosshardy** [comment]
At the current time we are not permitted by our company to open source our efforts, however we would like to contribute it back to the community so others can benefit from it as we benefit from much open-source. We are working on changing our company's position on this. If that happens, we would be happy to share it.  

Thank you for looking into it promptly!

**Comment by RomanGotsiy** [comment]
Fixed! Will be released in the upcoming alpha.

> At the current time we are not permitted by our company to open source our efforts

Could you at least share a screenshot or a gif of it with me privatelly? E.g. DM on twitter. I'm super curious 🤓

**Comment by rosshardy** [comment]
Yes. E-mailed it to you. Thanks again for the prompt turnaround!

**Comment by rosshardy** [comment]
@RomanGotsiy any estimate when the next alpha build will be released? Thank you.

**Comment by RomanGotsiy** [comment]
Will be released early this week.

**Comment by rosshardy** [comment]
> Will be released early this week.

Will the release be coming soon? Thanks!

**Comment by RomanGotsiy** [comment]
@rosshardy Check out `redoc@2.0.0-rc.0` or use `redoc@next`

**Comment by osamaramihafez** [comment]
Is there a reason this slugify error may occur inside of a json file? I've been looking for a while but I haven't found anything simlar to a hyphen without a string. The error message isn't very descriptive and I can't really figure out what's wrong.

```
Something went wrong...
slugify: string argument expected
Stack trace
Error: slugify: string argument expected
    at n (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:77206)
    at fe (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:21266)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:25452)
    at Function.e.getTagGroupsItems (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:27224)
    at Function.e.buildStructure (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:26607)
    at new ra (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:25186)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:89534)
    at t.makeStore (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:71303)
    at t.render (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:72261)
    at Fa (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:72:69876)

ReDoc Version: 2.0.0-rc.53
Commit: 5c8524d
```
