### ISSUE TITLE
Ignored incorrect HTTP response status code

### ISSUE THREAD

**Issue by g0194776** [Rebilly/ReDoc#836]
Hi guys,

After I ran up a docker container of ReDoc, the web page immediately returns a fault which listed below:
```plain
Something went wrong...
invalid HTTP code
Stack trace
Error: invalid HTTP code
    at He (http://127.0.0.1:32770/redoc.standalone.js:107:25389)
    at http://127.0.0.1:32770/redoc.standalone.js:107:50285
    at Array.filter (<anonymous>)
    at e.get (http://127.0.0.1:32770/redoc.standalone.js:107:50232)
    at e.get [as responses] (http://127.0.0.1:32770/redoc.standalone.js:107:29079)
    at http://127.0.0.1:32770/redoc.standalone.js:113:85724
    at di (http://127.0.0.1:32770/redoc.standalone.js:68:65399)
    at Vi (http://127.0.0.1:32770/redoc.standalone.js:68:78336)
    at Qi (http://127.0.0.1:32770/redoc.standalone.js:68:78713)
    at Pa (http://127.0.0.1:32770/redoc.standalone.js:68:85136)

ReDoc Version: 2.0.0-rc.2 
Commit:
```
How to ignore incorrect HTTP status code?

Thanks,
Kevin Yang

**Comment by RomanGotsiy** [comment]
Why do you need ignoring invalid HTTP status code versus fixing it?

**Comment by g0194776** [comment]
@RomanGotsiy 

We don't apply RESTful design pattern to ours API interface design. It always returns 200/OK for each of HTTP response but with different HTTP body.  for example:

```text
HTTP 200/OK

{
    "error-id": 40000,
    "reason": "xxxxxxxx"
}
```

That's why we need to show different HTTP response error under the  ReDoc "Responses" list. Currently, Swagger does,  but ReDoc doesn't properly recognize those of customized HTTP response.

**Comment by RomanGotsiy** [comment]
Use just `200` in the OpenAPI file, not `200/OK`. Status code must be a three-digit integer according to the [RFC7231](https://tools.ietf.org/html/rfc7231#section-6)
