### ISSUE TITLE
Redoc-cli@0.8.2 cannot find module 'base64-js"

### ISSUE THREAD

**Issue by joachimgoo** [Rebilly/ReDoc#850]
Hi
Redoc-cli gives me the following error: Error: Cannot find module 'base64-js'
Version: 0.8.2

```
$ npm i -g redoc-cli
/Users/x/.npm-packages/bin/redoc-cli -> /Users/x/.npm-packages/lib/node_modules/redoc-cli/index.js

> fsevents@1.2.7 install /Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote

> styled-components@4.1.3 postinstall /Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
+ redoc-cli@0.8.2
added 391 packages from 222 contributors in 6.799s
$ redoc-cli serve ecommerce-platform.json
module.js:550
    throw err;
    ^

Error: Cannot find module 'base64-js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6145:18)
    at __webpack_require__ (/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:36:30)
    at Object.<anonymous> (/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:1113:14)
    at Object.<anonymous> (/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:2893:30)
    at __webpack_require__ (/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:36:30)
    at Object.<anonymous> (/Users/x/.npm-packages/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6139:41)
```

**Comment by RomanGotsiy** [comment]
Finally `0.8.3` resolves all the CLI issues. Tested it out now on a separate machine.

Should add a test to CI
