### ISSUE TITLE
 Error: Can't resolve 'null',  Redoc Standalone

### ISSUE THREAD

**Issue by imdugud** [Rebilly/ReDoc#930]
Hello 

I am using redoc version 2.0.0-rc.8-1. 
My code;

<div class="redoc-container"></div>

import redoc from "redoc/bundles/redoc.standalone";

redoc.init(this.swaggerObj, {
      scrollYOffset: 50
    }, document.getElementById('redoc-container'))

I also tried import as { RedocStandalone }, { init } and { Redoc } , but didn't work.

I got this browser error;

redoc.standalone.js?1c32:7 Uncaught Error: Cannot find module 'null'
    at webpackMissingModule (redoc.standalone.js?1c32:7)
    at eval (redoc.standalone.js?1c32:7)
    at eval (redoc.standalone.js?1c32:7)
    at Object../node_modules/redoc/bundles/redoc.standalone.js (build.js:15642)
    at __webpack_require__ (build.js:20)
    at eval (Documentation.vue?3a40:10)
    at Object../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/components/api-detail/Documentation.vue?vue&type=script&lang=js& (build.js:1399)
    at __webpack_require__ (build.js:20)
    at eval (Documentation.vue?7f4d:1)
    at Module../src/components/api-detail/Documentation.vue?vue&type=script&lang=js& (build.js:18278)

What I'm doing wrong there?

Thanks for  your help.

**Comment by RomanGotsiy** [comment]
`import { RedocStandalone } from 'redoc';`

**Comment by imdugud** [comment]
Unfortunatelly, this time webpack gave "Can't resolve 'styled-components' and 'mobx' errors. 

Then, I installed "react react-dom mobx@^4.2.0 styled-components" packages. 

Rewrite my code and I got an error as follows;

react.development.js?72d0:388 Uncaught (in promise) TypeError: Cannot set property 'props' of undefined
    at PureComponent (webpack-internal:///./node_modules/react/cjs/react.development.js:388:14)
    at RedocStandalone (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:13157:42)
    at VueComponent._callee$ (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/components/api-detail/Documentation.vue?vue&type=script&lang=js&:36:42)
    at tryCatch (webpack-internal:///./node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/components/api-detail/Documentation.vue?vue&type=script&lang=js&:14:103)
    at _next (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/components/api-detail/Documentation.vue?vue&type=script&lang=js&:16:194)
    at <anonymous>


I try to use redoc at my vue project. Is there any other option to use with vue?

**Comment by tindleaj** [comment]
I came up with a workaround that allowed me to embed the redoc component in an Angular7 app. I posted it in [this issue thread](https://github.com/Redocly/redoc/issues/669#issuecomment-510941907).
